general:
  project: qwiklabs-gcp-04-424f1fdacc59
  region: us-west1-b
  model_name: mubi-reco
  bucket: mubi-kfp-artifact-store
  # timestamp: 20220310101753 #full dataset
  timestamp: 20220311093210

data_preprocessing:
  dataset_id: mubi_movie_data
  output_filename:
    train: train_mubi.tfdataset
    validation: validation_mubi.tfdataset
    inference: inference_mubi.tfdataset
    movies: movies_mubi.tfdataset